// API REST de Usuários
@baseURL = http://localhost:3000/user
@id = 1
###
// GET 
GET {{baseURL}}
Content-Type: application/json

###
// GET - By id
GET {{baseURL}}/{{id}}
Content-Type: application/json

###
//POST
POST {{baseURL}}
Content-Type: application/json

{
    "nome": "UserTes123t2",
    "telefone": "(12) 34567-8901",
    "email": "usertestasd1email@gmail.com",
    "senha": "user1password1234",
    "cpf": "123.456.789-02",
    "cep": "121345-678",
    "cidade": "USer1 City TestCityName",
    "bairro": "User1 Neigborhood TestNeigborhoodName",
    "rua": "User1 Rua TestRuaName",
    "numero": 123,
    "complemento": " ",
    "nivel": 0
}

###
//PUT
PUT {{baseURL}}/{{id}}
Content-Type: application/json

{
    "nome": "UserTes123t2",
    "telefone": "(12) 34567-8901",
    "email": "usertestasd1email@gmail.com",
    "senha": "user1password1234",
    "cpf": "123.456.789-02",
    "cep": "121345-678",
    "cidade": "USer1 City TestCityName",
    "bairro": "User1 Neigborhood TestNeigborhoodName",
    "rua": "User1 Rua TestRuaName",
    "numero": 123,
    "complemento": " ",
    "nivel": 1
}

###
//DELETE
DELETE {{baseURL}}/{{id}}
Content-Type: application/json
